### ISSUE TITLE
As B2B User, I should be able to view Quick Order from my account

### ISSUE THREAD

**Issue by kibo-sushant** [KiboSoftware/nextjs-storefront-b2b#19]
A B2B user should be able to view Quick Order in the same B2B account from a link, titled "Quick Order" in the My Account section.

**Desktop view should display following fields.**
1. 'Quick Order' as heading.
2. 'Initiate Quote' and 'Checkout' button
3. Search input field with 'Search for a product' title and 'Search by product name or code' as placeholder text
4. or 'import list' link 
5. Product List table (with scrollbar)
   a) product
   b) Assembly
   c) Fulfillment method
   d) Quantity 
   e) Price
   
6. Coupon input field with 'Coupon' as title and 'Enter Coupon Code' as placeholder text
7. 'Apply' button
8. 'Order Total' read-only field

**Mobile view should display following fields (Most of the fields are similar to Desktop except the following).**
1. 'Cart' as heading
2. should display 'Add to Cart' button along with 'Product Search' input field
3. should display 'Cards.'
4. should display 'Edit' and 'Delete' icons

**Functionality**
User should be able to search using 'Search for a product.'
User should be able to select any product from search suggestion list.
User should be able to see selected products under table.
User should be able to import existing list using 'import a list' link.
User should be able to apply valid Coupon. 
User should be able to see modified 'Order Total', after applying valid Coupon.
User should be able to modify 'Assembly', 'Fulfillment method' and 'Quantity'

**Comment by kibo-geetanshuchhabra** [comment]
Completed all the functionality in this ticket. (https://github.com/KiboSoftware/nextjs-storefront-b2b/issues/30)

PR Link: https://github.com/KiboSoftware/nextjs-storefront-b2b/pull/72
