### ISSUE TITLE
As a B2B User, I should be able to view shared b2b lists from my account

### ISSUE THREAD

**Issue by kibo-kevinwatts** [KiboSoftware/nextjs-storefront-b2b#6]
Add a new link inside My Account titled "lists" This should route to "/my-account/b2b-users"

https://www.figma.com/file/bKJuIwUx6VXmubHZo4rCBq/B2B?node-id=211-11845&t=zhQPXdByEKEdXPMT-0

Create a new Page Template that contains the list view

https://www.figma.com/file/bKJuIwUx6VXmubHZo4rCBq/B2B?node-id=211-11874&t=zhQPXdByEKEdXPMT-0

**Comment by kibo-sushant** [comment]
// mutation

```
query wishlists {
  wishlists {
    items {
      customerAccountId
      id
      name     
      userId
              
      auditInfo {
        createBy
        createDate
      }
  
    }  
  }
}
```
